### PR TITLE
Add license

### LINKED ISSUE #14: Missing licenses
### Description

I'd suggest using:

- [MIT](https://opensource.org/license/MIT) for all the codebase.
- [CC BY 4.0 International](https://creativecommons.org/licenses/by/4.0/) for all the content.

Why use a license? Without a license, no one knows if they can contribute, use the content, or even share it.
You should check out https://opensource.guide/legal/ for more useful information.

**EDIT:** The license and author of the header image should also be mentioned somewhere on the readme/license files.

### PR DESCRIPTION
**Pull request by a-blob**
Fixes #14

### CODE REVIEW

**Review by src4026 — COMMENTED** [review]
Everything looks good to me 👍 
Although we were going to add a separate license for the website code too iirc?

**Comment by a-blob** [comment]
Is that needed? The code is generated by Writerside based on the .md files, and not programmed by us.

**Comment by src4026** [comment]
> Is that needed? The code is generated by Writerside based on the .md files, and not programmed by us.

Hmm, yeah. Not sure about adding licenses for that personally too anyway. :thumbsup:

**Review by src4026 — APPROVED** [review]

**Comment by Panquesito7** [comment]
> Is that needed? The code is generated by Writerside based on the .md files, and not programmed by us.

I see. But what if someone else wants to take code from here? How will they know what they can do with it and what they can't?

**Comment by src4026** [comment]
> > Is that needed? The code is generated by Writerside based on the .md files, and not programmed by us.
> 
> I see. But what if someone else wants to take code from here? How will they know what they can do with it and what they can't?

As per our internal consensus, we could apply the license to the code of the handbook as it's mixed along with it.

**Pull request merged**
